### PR TITLE
Fix phpunit deprecation

### PR DESCRIPTION
**Pull request by shmax**
`expectExceptionMessageRegExp` was deprecated in PHPUnit 8.4, and will be removed in 9.0. Migration seems easy enough...

### CODE REVIEW

**Comment by shmax** [comment]
Ah, I see we support both phpunit 7.2 and 8.5. I guess we have to just sort of live with this for a while?

**Comment by simPod** [comment]
TBH I'd rather wait with this for #470 and then solve it only for latest compatible phpunit version.

**Comment by shmax** [comment]
> I'd rather wait with this for #470 and then solve it only for latest compatible phpunit version.

Sure, but there's no harm in merging, this, is there? Those warnings are a big distraction, and we can always touch this up if you ever sort out #470

**Comment by simPod** [comment]
Seemed like a bit of pollution to me but ofc it depends on a roadmap. If @vladar does not plan to drop 7.1 support soon this can be merged I guess.

**Comment by shmax** [comment]
Thanks much!

**Pull request merged**
