### PR TITLE
Do not specify test groups when running tests in CI

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by vladar** [comment]
Why not? We actually exclude ReactPromise from the default test group. But we still want to test it in Travis.

**Comment by simPod** [comment]
Ah I see it is excluded in phpunit dist. Why is it so?

**Comment by vladar** [comment]
Because it is an optional feature which relies upon ReactPHP promises which is not installed by default (it is suggested in the composer config, not required)

**Comment by simPod** [comment]
What if I make ReactPHP promises dev dependency and therefore simple `vendor/bin/phpunit` can be used without any group exclusion anywhere?

**Pull request closed without merging**
