### PR TITLE
Port 0.12.3 changes from graphql-js

### PR DESCRIPTION
**Pull request by danez**
Instead of doing one PR for each and every change I now decided to do everything in one branch because I started getting tons of merge conflicts as the changes usually depend on other changes.

For review each commit could be reviewed separately.

I hope this is okay, I know that huge PRs are a pain to review, but otherwise it would block me completely.

I will list the changes here:

## 0.12.3

- [ ] [Fix how TypeInfo handles inline fragments without type](https://github.com/webonyx/graphql-php/pull/248/commits/eb9ac66af8c493a04c29816fe5946981851a1ac0) | graphql/graphql-js#1041
- [ ] [Uniform parsing of queries with short-hand syntax with regular queries](https://github.com/webonyx/graphql-php/pull/248/commits/46816a7cdad856ac310c721c0d5c37de8dc54e23) | graphql/graphql-js#1094
- [ ] [RFC: Block String](https://github.com/webonyx/graphql-php/pull/248/commits/8747ff8954d65533da7a0f8d99fd16c4b5ba1201) | graphql/graphql-js#926
- [ ] [Improvements to printing block strings](https://github.com/webonyx/graphql-php/pull/248/commits/e65638f6f42d81666a3bde2702d72a251df3612b) | graphql/graphql-js@f9e67c403a4667372684ee8c3e82e1f0ba27031b
- [ ] [RFC: Descriptions as strings](https://github.com/webonyx/graphql-php/pull/248/commits/022c49001142f4c3ae1382181d31299feef45541) | graphql/graphql-js#927 | BREAKING CHANGE: This does not parse descriptions from comments by default anymore and the value of description in Nodes changed from `string` to `StringValueNode`
- [ ] [Fix print of block string with leading space and quotation](https://github.com/webonyx/graphql-php/pull/248/commits/7705e50e441d293a7a24b3e1b189299c43ceb9fe) | graphql/graphql-js#1190
- [ ] [Support for union/interface types when using buildSchema](https://github.com/webonyx/graphql-php/pull/248/commits/4e26de3588ef6657e9bc0aa31227789be82057a6) | graphql/graphql-js#947
- [ ] [Add additional number lexing test](https://github.com/webonyx/graphql-php/pull/248/commits/98e397ce447d29fba53dd4b1acb571650d2bca7c) | graphql/graphql-js@72421378550cf51b13c6db59b8fc912591fd1a4b
- [ ] [Remove notes about subscription being experimental](https://github.com/webonyx/graphql-php/pull/248/commits/1fdb3da7fbce5f01bc569f872c251779b84fd8ba) | graphql/graphql-js@bf4a25a33a62280e82680518adc279e34ec816e0
- [ ] [Simplify operationTypes validation](https://github.com/webonyx/graphql-php/pull/248/commits/17a8c26fc95df8dca9b8806e28d67a5aac2a6a82) | graphql/graphql-js#999
- [ ] [Detect added nullable input field or added nullable argument](https://github.com/webonyx/graphql-php/pull/248/commits/2123946dbd14fdadad78821ee7ecf3de772bc119) | graphql/graphql-js#1096 | graphql/graphql-js@db4cfdc
- [ ] [Fix parsing of default values in build-schema](https://github.com/webonyx/graphql-php/pull/248/commits/27ce24b5fe051ae7cd095de989845efc2641a4c2) | graphql/graphql-js#903 | graphql/graphql-js@714ee98
- [ ] [(Potentially Breaking) Allow serializing scalars as null.](https://github.com/webonyx/graphql-php/pull/248/commits/48c33302a8ccaf32ca50ac27ec57abb4bb807f88) | graphql/graphql-js#1104
- [ ] [Remove duplicated code from buildASTSchema and extendSchema](https://github.com/webonyx/graphql-php/pull/248/commits/2cbccb87db75f6b68ceb0dbb7997b3821c4ee065) | graphql/graphql-js#1000 | BREAKING CHANGE: SchemaBuilder::build() and buildAST() and constructor removed the typedecorator, as not needed anymore as library can now resolve union and interfaces from generated schemas, see commit above.
- [ ] [Allow to extend GraphQL errors with additional properties](https://github.com/webonyx/graphql-php/pull/248/commits/c4f11a577e6dab67174d8ff586f3a55a19159d74) | graphql/graphql-js#928
- [ ] [Add predicates to for built-in types](https://github.com/webonyx/graphql-php/pull/248/commits/1da38016148288ab2b005069dd9a653077acb3b6) | graphql/graphql-js#924
- [ ] [Update to match SDL changes](https://github.com/webonyx/graphql-php/pull/248/commits/d70a9a5e538ce0028bd50b27501ba979071b2761) | graphql/graphql-js#1102
- [ ] [Fix infinite loop on invalid queries in OverlappingFields](https://github.com/webonyx/graphql-php/pull/248/commits/6e358eb26cdfd707a17470e63ee41ebccb967e10) | graphql/graphql-js#1111
- [ ] [Improve introspection types + new getIntrospectionQuery()](https://github.com/webonyx/graphql-php/pull/248/commits/ff63e07b05e5973af0a0c646f8ca4da2a4809f71) | graphql/graphql-js#1113
- [ ] [Read-only AST types](https://github.com/webonyx/graphql-php/pull/248/commits/74854d55a099f6db1629a92d744b77b0548093d0) | graphql/graphql-js#1121
- [ ] [SDL Spec changes](https://github.com/webonyx/graphql-php/pull/248/commits/b5106a06c9ebf5bfb24db4087ca9a5200c38f93a) | graphql/graphql-js#1117
- [ ] [Allow constructing GraphQLError with single node.](https://github.com/webonyx/graphql-php/pull/248/commits/0c984a83bb61584e9379f3b9142dde1dbf8cbb45) | graphql/graphql-js#1123
- [ ] [Include test that printSchema includes non-spec directives.](https://github.com/webonyx/graphql-php/pull/248/commits/481cdc9a82936dfcbf6c333a1f0b4b64fde6f929) | graphql/graphql-js@007407d
- [ ] [Fix unhandled error when parsing custom scalar literals.](https://github.com/webonyx/graphql-php/pull/248/commits/f661f3821574147e7ed7ea952d5163ca2650576c) | graphql/graphql-js#1126
- [ ] [New: printError()](https://github.com/webonyx/graphql-php/pull/248/commits/15374a31dd26a3ae5e9fe14700f761b900be3490) | graphql/graphql-js#1129 | BREAKING CHANGE: The SyntaxError message does not contain the codeframe anymore and only the message, (string) $error will print the codeframe.
- [ ] [Validate schema root types and directives](https://github.com/webonyx/graphql-php/pull/248/commits/06c6c4bd975190cba572d341e8929ea1ed1b9825) | graphql/graphql-js#1124
- [ ] [Fix printError/locations for multiple nodes.](https://github.com/webonyx/graphql-php/pull/248/commits/cf276340a4249fb426a6c4fa940fb0e5fcbd455c) | graphql/graphql-js#1131
- [ ] [Always extract extensions from the original error if possible](https://github.com/webonyx/graphql-php/pull/248/commits/cf276340a4249fb426a6c4fa940fb0e5fcbd455c) | graphql/graphql-js@2d08496720088dbe65ebea312c8526bd48fb8ee8
- [ ] [Preserve original coercion errors, improve error quality.](https://github.com/webonyx/graphql-php/pull/248/commits/60df83f47e5bddc9315e725c0a779f7eeb249c4f) | graphql/graphql-js#1133
- [ ] [Better Predicates](https://github.com/webonyx/graphql-php/pull/248/commits/9387548aa1f297f4dbda8acbcf07d66b323abaa8) | graphql/graphql-js#1137
- [ ] [Fix Bug in PossibleFragmentSpreads validator](https://github.com/webonyx/graphql-php/pull/248/commits/50cbfb4a44615e6f2bad427b5f5e87409ebb8307) | graphql/graphql-js@7e147a8
- [ ] [Address recent SDL spec changes](https://github.com/webonyx/graphql-php/pull/248/commits/6d08c342c9ec0959d68e78da28f66ac17736424c) | graphql/graphql-js#1139
- [ ] [Move schema validation into separate step (type constructors)](https://github.com/webonyx/graphql-php/pull/248/commits/97e8a9e2007754a2d0ee7f27ae78c82ee4c7dafe) | graphql/graphql-js#1132
- [ ] [Robust type info](https://github.com/webonyx/graphql-php/pull/248/commits/fde7df534d78551d97049be8136de52a4d6c0a42) | graphql/graphql-js#1143
- [ ] [Add experimental support for parsing variable definitions in fragments](https://github.com/webonyx/graphql-php/pull/248/commits/949b85367826b30dd7c19d5578281fed5dc93fd4) | graphql/graphql-js#1141
- [ ] [Update some validators to latest upstream version](https://github.com/webonyx/graphql-php/pull/248/commits/17520876d86f3ab2d83156927bf7b65f59bd7063) | graphql/graphql-js#355 graphql/graphql-js#1147
- [ ] [Validate literals in a single rule with finer precision](https://github.com/webonyx/graphql-php/pull/248/commits/58e0c7a178154203c7aec9108102805ae8db23c2) | graphql/graphql-js#1144
- [ ] [Fix path argument. Enchance visit test to validate all arguments](https://github.com/webonyx/graphql-php/pull/248/commits/ddfeee314c97a1e7d3efbff35646248db230533e) | graphql/graphql-js#1149
- [ ] [Find breaking directive changes](https://github.com/webonyx/graphql-php/pull/248/commits/d71b45d60ef40740833b9f76e654d16c175eb844) | graphql/graphql-js#1152
- [ ] [Add suggestions for invalid values](https://github.com/webonyx/graphql-php/pull/248/commits/d92a2dab217c01512c2a0b7d56dcb6783ca10afa) | graphql/graphql-js#1153

## Fixes not related to 0.12 or 0.13

- [ ] [Fix KnownDirectives validator to support all directives](https://github.com/webonyx/graphql-php/pull/248/commits/0c329821715fc82f08d7443dc474555c667a5078)
- [ ] [Improve validation error message when field names conflict](https://github.com/webonyx/graphql-php/pull/248/commits/58453c31f78dc5c6d9cee00cd70f55dea471dbfb) | graphql/graphql-js#363
- [ ] [Validation: improving overlapping fields quality](https://github.com/webonyx/graphql-php/pull/248/commits/7b05673d8d9864ad700a6b6bdbfaac70cbbce9ee) | graphql/graphql-js#386
- [ ] [Adding an interface to a type is now a dangerous change.](https://github.com/webonyx/graphql-php/pull/248/commits/48c5e64a088f23f211dea3568ec0196138bda3c1) | graphql/graphql-js#992

## Docs

- [ ] [1](https://github.com/webonyx/graphql-php/pull/248/commits/d6add77540d3133fe4829da6fc863c5cd48efbe2)

### CODE REVIEW

**Comment by vladar** [comment]
Awesome, let me know when you are done, I'll review and merge it. Thanks!

**Comment by danez** [comment]
Okay I added all the relevant commits from 0.11 till 0.12.3 from graphql-js.
There are a couple of breaking changes, most of them I either already added to UPGRADE doc or made them backwards compatible.

Major changes are the new SchemaDefinitionLanguage from the spec, a new SchemaValidator,  updated validation rules, more breaking changes detection.

Lots of validations stuff was already removed from the constructor here, which they now also did in the  JS library. I tried to sync the two libraries in this topic and moved some logic from TypeClasses (for example Directive) to the `SchemaValidationContext`.
There are still some checks left in Type::assertValid() but most of them are now not related anymore to the Schema but more to the configuration of the types (ala checking if typeresolver is function etc.) Maybe this can now be cleaned up better than the current status.
I thought about moving all the new Validation of the Schema to the corresponding Type classes, but that way it will be way harder to make updates from upstream, so I left it for now in the SchemaValidationContext.

I also run phpbench. Before
```
❯ bin/phpbench run
PhpBench 0.15-dev (@git_version@). Running benchmarks.
Using configuration file: /Users/danieltschinder/Documents/Github/graphql-php/phpbench.json

\GraphQL\Benchmarks\HugeSchemaBench

    benchSchema                   I0 P0 	[μ Mo]/r: 156.042 156.042 (ms) 	[μSD μRSD]/r: 0.000ms 0.00%
    benchSchemaLazy               I0 P0 	[μ Mo]/r: 0.010 0.010 (ms) 	[μSD μRSD]/r: 0.000ms 0.00%
    benchSmallQuery               I0 P0 	[μ Mo]/r: 72.225 72.225 (ms) 	[μSD μRSD]/r: 0.000ms 0.00%
    benchSmallQueryLazy           I0 P0 	[μ Mo]/r: 55.960 55.960 (ms) 	[μSD μRSD]/r: 0.000ms 0.00%

\GraphQL\Benchmarks\StarWarsBench

    benchSchema                   I1 P0 	[μ Mo]/r: 0.142 0.142 (ms) 	[μSD μRSD]/r: 0.001ms 0.35%
    benchHeroQuery                I1 P0 	[μ Mo]/r: 0.910 0.910 (ms) 	[μSD μRSD]/r: 0.015ms 1.64%
    benchNestedQuery              R2 I1 P0 	[μ Mo]/r: 2.170 2.170 (ms) 	[μSD μRSD]/r: 0.088ms 4.06%
    benchQueryWithFragment        R2 I1 P0 	[μ Mo]/r: 2.442 2.442 (ms) 	[μSD μRSD]/r: 0.104ms 4.24%
    benchStarWarsIntrospectionQueryR2 I1 P0 	[μ Mo]/r: 23.936 23.936 (ms) 	[μSD μRSD]/r: 0.057ms 0.24%

\GraphQL\Benchmarks\LexerBench

    benchIntrospectionQuery       R2 I4 P0 	[μ Mo]/r: 1.327 1.337 (ms) 	[μSD μRSD]/r: 0.021ms 1.59%

10 subjects, 19 iterations, 170 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 0.010 [31.516 31.517] 0.010 (ms)
⅀T: 350.073ms μSD/r 0.029ms μRSD/r: 1.212%
```

and after

```
❯ bin/phpbench run
PhpBench 0.15-dev (@git_version@). Running benchmarks.
Using configuration file: /Users/danieltschinder/Documents/Github/graphql-php/phpbench.json

\GraphQL\Benchmarks\HugeSchemaBench

    benchSchema                   I0 P0 	[μ Mo]/r: 146.235 146.235 (ms) 	[μSD μRSD]/r: 0.000ms 0.00%
    benchSchemaLazy               I0 P0 	[μ Mo]/r: 0.009 0.009 (ms) 	[μSD μRSD]/r: 0.000ms 0.00%
    benchSmallQuery               I0 P0 	[μ Mo]/r: 58.761 58.761 (ms) 	[μSD μRSD]/r: 0.000ms 0.00%
    benchSmallQueryLazy           I0 P0 	[μ Mo]/r: 54.593 54.593 (ms) 	[μSD μRSD]/r: 0.000ms 0.00%

\GraphQL\Benchmarks\StarWarsBench

    benchSchema                   I1 P0 	[μ Mo]/r: 0.152 0.152 (ms) 	[μSD μRSD]/r: 0.005ms 3.38%
    benchHeroQuery                I1 P0 	[μ Mo]/r: 0.929 0.929 (ms) 	[μSD μRSD]/r: 0.006ms 0.65%
    benchNestedQuery              I1 P0 	[μ Mo]/r: 2.197 2.197 (ms) 	[μSD μRSD]/r: 0.025ms 1.13%
    benchQueryWithFragment        I1 P0 	[μ Mo]/r: 2.630 2.630 (ms) 	[μSD μRSD]/r: 0.101ms 3.85%
    benchStarWarsIntrospectionQueryI1 P0 	[μ Mo]/r: 24.592 24.593 (ms) 	[μSD μRSD]/r: 0.844ms 3.43%

\GraphQL\Benchmarks\LexerBench

    benchIntrospectionQuery       I4 P0 	[μ Mo]/r: 1.339 1.348 (ms) 	[μSD μRSD]/r: 0.021ms 1.60%

10 subjects, 19 iterations, 170 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 0.009 [29.144 29.145] 0.009 (ms)
⅀T: 327.296ms μSD/r 0.100ms μRSD/r: 1.404%
```

So the `benchSchema` seems to have gotten a little bit faster and also the `benchSmallQuery`

Let me know what you think, and sorry again for the huuuuggggeee PR. If I can help you somehow with reviewing let me know. I created the checkboxes in the initial description that you might want to use to tick reviewed commits if you want to do reviews based on commits.

**Comment by vladar** [comment]
This is fantastic! I wanted to port these changes in near future, just couldn't find big-enough time window (as I've been quite busy recently). So your PR is sooo helpful, thanks again! But reviewing it will also take some time %)

**Comment by vladar** [comment]
One major problem is a removal of a `typeConfigDecorator` from the `buildSchema`. We actually used it to attach resolvers to fields and types. Not just to make interfaces and unions resolvable.

As far as I understand regular buildSchema doesn't allow you to do this and just asks to rely on root value for resolution process? If so, then this is something we will probably have to revert.

**Comment by danez** [comment]
Okay I understand, I will add it back.

**Comment by danez** [comment]
Okay I added it back and also fixed a bug with the lazy loading of types which I introduced.

**Comment by vladar** [comment]
Merged! One final thing that concerns me is that we expose `Utils::undefined()` in scalars types. It is kinda hack to simplify maintenance and was not supposed to be exposed to library users (and it will happen when users will start building their custom types looking at existing internal types).

How do you think can we just throw instead of returning undefined? Looks like exceptions in those methods are handled correctly, so there shouldn't be a major difference, right?

**Comment by vladar** [comment]
And thank you so much for this huge work!

**Comment by danez** [comment]
🎉 Feel free to ping me if bugs come up.

**Comment by vladar** [comment]
@danez So any ideas about throwing vs returning `Utils::undefined()` (see the [comment above](https://github.com/webonyx/graphql-php/pull/248#issuecomment-376039018)). Will it work, how do you think?

**Comment by danez** [comment]
Ah sorry I missed that comment. Yes good point, I guess throwing would have the same effect as `Utils::undefined()`.
We just need to make sure that `null` isn't used for this as it can always be a valid value.

**Comment by danez** [comment]
I will create a PR to do the `Utils:undefined()` vs `throw` change ASAP.

**Comment by vladar** [comment]
Cool, as soon as we switch to throw vs `Utils::undefined()`, I'll release version 0.12. Thanks!

**Pull request merged**
