### PR TITLE
Optimized implementation to interfaces loading

### PR DESCRIPTION
**Pull request by mcg-web**
* Optimized implementation to interfaces using lazy loader.
* Union types now accepting callback

### CODE REVIEW

**Comment by vladar** [comment]
I am ready yo merge this, but just curious - what is your use case that requires lazy initialization of interface implementations?

**Comment by mcg-web** [comment]
The use case is simple let say we have this:

```
interface A {}
type B implement A {}
```

```php
new ObjectType([
      "name" => "B",
      "fields" => [/*...*/],

]);
```

**Comment by vladar** [comment]
Yeah, looks like you are right. I will also rework test case for interface definition via Closure to check for this.

**Comment by mcg-web** [comment]
Yes the test will help for no BC on later modifications :+1:

**Pull request merged**
