### PR TITLE
Allow lazy input object fields

### LINKED ISSUE #911: Lazy field definitions not working for Input types
[Release v14.7.0](https://github.com/webonyx/graphql-php/releases/tag/v14.7.0) allows providing field definitions as a callable and resolve them lazily, thanks to the great work by @stayallive in PR #871 

I was trying to port our codebase so that fields are resolved lazily, and noticed that this feature does not work for input object types.

@stayallive [suggested](https://github.com/webonyx/graphql-php/pull/861#issuecomment-892093535) I open an issue.

You can add this test below to `DefinitionTest.php` to reproduce the issue:

```php
    /**
     * @see it('allows an input type to define its fields as closure returning array field definition to be lazy loaded')
     */
    public function testAllowsInputTypeWhichDefinesItFieldsAsClosureReturningFieldDefinitionAsArray() : void
    {
        $objType = new InputObjectType([
            'name'   => 'SomeInputObject',
            'fields' => [
                // 'f' => ['type' => Type::string()],
                'f' => static function () : array {
                    return ['type' => Type::string()];
                },
            ],
        ]);

        $objType->assertValid();

        self::assertSame(Type::string(), $objType->getField('f')->getType());
    }
```

This test will fail. 
```
./vendor/bin/phpunit --filter testAllowsInputTypeWhichDefinesItFieldsAsClosureReturningFieldDefinitionAsArray
PHPUnit 8.5.19 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 250 ms, Memory: 14.00 MB

There was 1 error:

1) GraphQL\Tests\Type\DefinitionTest::testAllowsInputTypeWhichDefinesItFieldsAsClosureReturningFieldDefinitionAsArray
TypeError: Return value of GraphQL\Type\Schema::resolveType() must be an instance of GraphQL\Type\Definition\Type, array returned

graphql/graphql-php/src/Type/Schema.php:406
graphql/graphql-php/src/Type/Definition/InputObjectField.php:121
graphql/graphql-php/src/Type/Definition/InputObjectField.php:148
graphql/graphql-php/src/Type/Definition/InputObjectType.php:117
graphql/graphql-php/tests/Type/DefinitionTest.php:1920

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

The code in the comment `// 'f' => ['type' => Type::string()],` will pass, since it is not using a callable.

This is a promising feature, I can see some gains already, but we have a lot of input types that could be converted, it would be great if this was supported for them as well.

Thanks a lot.

### PR DESCRIPTION
**Pull request by spawnia**
Resolves #911

@stayallive @sebastienbarre

### CODE REVIEW

**Comment by sebastienbarre** [comment]
Thanks @spawnia , I'll try to test it out soon!

**Comment by sebastienbarre** [comment]
Sorry, I can't seem to be able to test it.
```
    "webonyx/graphql-php": "dev-master",
```
is not updating my app correctly.
```
composer upgrade webonyx/graphql-php                                          2 ✘  01:36PM
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mll-lab/graphql-php-scalars is locked to version v3.1.0 and an update of this package was not requested.
    - mll-lab/graphql-php-scalars v3.1.0 requires webonyx/graphql-php ^0.13.8 || ^14.0.0 -> found webonyx/graphql-php[v0.13.8, v0.13.9, 0.13.x-dev, v14.0.0, ..., 14.x-dev] but it conflicts with your root composer.json require (dev-master).
```

**Comment by stayallive** [comment]
You would need this probably since it's not in master and you will need to "trick" it to fix other dependencies complaining:

```json
	"webonyx/graphql-php": "dev-allow-lazy-input-object-fields as 14.9.0",
```

**Comment by sebastienbarre** [comment]
@stayallive thanks! I didn't know that trick, this is great.

@spawnia still trying to evaluate your change, thanks. This branch contains a fair amount of breaking changes (#906 and #830) that I'm trying to work around.

**Comment by sebastienbarre** [comment]
Thanks, this is passing all our tests, and provide a small speed-up, so I'll take it :)

**Review by simPod — APPROVED** [review]

**Pull request merged**
