### PR TITLE
Fix resolve Fn key

### PR DESCRIPTION
**Pull request by jbtbnl**
Otherwise all existing resolve functions on fields get lost.

### CODE REVIEW

**Comment by vladar** [comment]
Can you add a test case for this to avoid regressions in the future?

**Comment by jbtbnl** [comment]
@vladar @simPod this is a test case:

```php
<?php

$queryType = new \GraphQL\Type\Definition\ObjectType([
	'name' => 'Query',
	'fields' => [
		'hello' => [
			'type' => \GraphQL\Type\Definition\Type::string(),
			'resolve' => function() {
				return 'Hello World!';
			}
		],
	]
]);

$schema = new \GraphQL\Type\Schema([
	'query' => $queryType,
]);

$documentAST = \GraphQL\Language\Parser::parse('
extend type Query {
	misc: String
}
');

$extendedSchema = \GraphQL\Utils\SchemaExtender::extend($schema, $documentAST);
$helloResolveFn = $extendedSchema->getQueryType()->getField('hello')->resolveFn;

$assertTrue = call_user_func($helloResolveFn) === 'Hello World!';
```

Please advice where to add this. Or feel free to copy/alter it.

**Comment by simPod** [comment]
It seems weird to me that accessor `->resolveFn` is not consistent with `'resolve'` key 🤔

**Comment by vladar** [comment]
Thanks!

**Pull request merged**
