### PR TITLE
Make Hello World compatible with GraphiQL

### LINKED ISSUE #87: GraphiQL Introspection query fails on Hello World example
Both ChromeiQL and GraphiQL Feen produce the same error when run on the Hello World graphql example (but the curl examples work):
```json
{
  "errors": [
    {
      "message": "Syntax Error GraphQL request (1:2) Expected Name, found String \"query\"\n\n1: {\"query\":\"\\n  query IntrospectionQuery {\\n    __schema {\\n      queryType { name }\\n      mutationType { name }\\n      types {\\n        ...FullType\\n      }\\n      directives {\\n        name\\n        description\\n        args {\\n          ...InputValue\\n        }\\n        onOperation\\n        onFragment\\n        onField\\n      }\\n    }\\n  }\\n\\n  fragment FullType on __Type {\\n    kind\\n    name\\n    description\\n    fields {\\n      name\\n      description\\n      args {\\n        ...InputValue\\n      }\\n      type {\\n        ...TypeRef\\n      }\\n      isDeprecated\\n      deprecationReason\\n    }\\n    inputFields {\\n      ...InputValue\\n    }\\n    interfaces {\\n      ...TypeRef\\n    }\\n    enumValues {\\n      name\\n      description\\n      isDeprecated\\n      deprecationReason\\n    }\\n    possibleTypes {\\n      ...TypeRef\\n    }\\n  }\\n\\n  fragment InputValue on __InputValue {\\n    name\\n    description\\n    type { ...TypeRef }\\n    defaultValue\\n  }\\n\\n  fragment TypeRef on __Type {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n        }\\n      }\\n    }\\n  }\\n\",\"variables\":null}\n    ^\n",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by PowerKiKi**
This allow newcomers to follow documentation to get started and then
keep exploring with GraphiQL

Closes #87

### CODE REVIEW

**Comment by PowerKiKi** [comment]
As a sidenote if GraphiQL way of sending things becomes/became a de-facto standard, it might be worth considering a sort of helper so end-users don't have to re-implement JSON parsing.

**Comment by vladar** [comment]
@PowerKiKi Thanks for the PR!

**Comment by PowerKiKi** [comment]
Btw is there a Gitter or mailing list to talk about usage of this project ? Specifically I am interested in advice/experiences about integrating with doctrine...

**Comment by vladar** [comment]
@PowerKiKi Not really. At this point we don't have that many bug reports, so feel free to create an issue on Github for any questions / discussions. This way we can also keep the knowledge base in one location and don't split the community.

**Pull request merged**
