### PR TITLE
Revert "Optimize lazy types (#684)"

### PR DESCRIPTION
**Pull request by shmax**
This reverts commit 6096b0174c2b40f3bff9889f3a91dcf071bae933.

@mfn Reported that his graphql-laravel tests are breaking since we merged my optimizations. I think we're going to have to hide some previously public members, and try this again in a major version release.

### CODE REVIEW

**Comment by kandy** [comment]
Can you add link on broken test/build of graphql-laravel?

**Comment by kandy** [comment]
https://github.com/rebing/graphql-laravel/pull/645/checks?check_run_id=848330436

**Comment by mfn** [comment]
There was some errors in the test suite (shame on me 😅 ) but one real break was that, for lazy types, you're not supposed to access the _public_ property `->type` directly, instead you **have** to use the `->getType()` method.

----
I'm now putting on my practical hat: it doesn't matter for graphql-laravel, because there was release yet with `^14` of graphql-php. Insofar, the revert is not strictly necessary.

----
Taking off my practical hat: in strict semver, this is obviously a break in a minor version. But depending on how many already did you use, graphql-php might just get away with it and document that `->getType()` is generally required for `^14`

----
🤷‍♀️

**Comment by shmax** [comment]
@vladar What do you think? Is this revert necessary? Please advise.

**Comment by vladar** [comment]
Can we just add `__get`, `__isset` and `__set` fallback for `type` property strictly for backwards compatibility (with a deprecation notice)?

**Comment by shmax** [comment]
> Can we just add __get, __isset and __set fallback for type property strictly for backwards compatibility (with a deprecation notice)?

You mean as an interim fix until the next major version? Well, maybe, but I opened this PR 12 days ago as an emergency fix for people in the same situation as @mfn. No doubt you were busy with other things, but no one else has come forward since then, so do you think this PR is really necessary?

**Comment by vladar** [comment]
Agreed. Let's move on with deprecation in #702

**Pull request closed without merging**
