### PR TITLE
Test against PHP 7.4

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by vladar** [comment]
Can we mark nightly builds as can fail? As they fail %)

**Comment by simPod** [comment]
I suppose it it 🤔 

https://github.com/webonyx/graphql-php/pull/440/files#diff-354f30a63fb0907d4ad57269548329e3R35

**Comment by simPod** [comment]
I guess that was not the proper way to define it. Now should be fine.

**Comment by vladar** [comment]
Thanks!

**Pull request merged**
