### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by spawnia**

### CODE REVIEW

**Comment by mfn** [comment]
I was about to suggest why not enable `no_unused_imports` when I realized, it's not using php-cs-fixer; a feature sadly not supported by phpcs 😞

**Comment by simPod** [comment]
@mfn phpcs supports this, I guess it's just not enabled here. #466 blocked by #470

**Review by simPod — APPROVED** [review]

**Comment by mfn** [comment]
> phpcs supports this

Does it? Granted, I'm not familiar with phpcs but https://github.com/squizlabs/PHP_CodeSniffer/issues/801 leads me to assume otherwise.

**Comment by simPod** [comment]
@mfn see https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesunuseduses-

In PHPCS there IMO should not be any sniffs but the CS tool. Might lead to confusions like this.

**Comment by mfn** [comment]
> confusions

I'm already confused by linking to coding-standard vs. the phpcs issue I linked but .. I totally trust your judgement, I feel already bad for derailing here so much. Apologies.

**Comment by simPod** [comment]
There's phpcs tool for running sniffs and then there are coding standards that are basically rulesets composed of sniffs. Those rulesets are run via phpcs. And one such ruleset that is used here is maintained by Doctrine https://github.com/doctrine/coding-standard. 

One confusing thing is that there are sniffs in phpcs repository https://github.com/squizlabs/PHP_CodeSniffer, I'd separate it into two 🤷🏾‍♀️ . Hope that clears it up a bit ;)

**Pull request merged**
