### PR TITLE
Call previously unused methods `EnumType::parseValue()` and `EnumType::parseLiteral()`

### PR DESCRIPTION
**Pull request by spawnia**
This pull request continues work done by @ruudk in https://github.com/webonyx/graphql-php/pull/1007 and opens up more flexible ways of implementing enum types. Previously, the methods `EnumType::parseValue()` and `EnumType::parseLiteral()` were defined but not used. Now they are used during the appropriate phases of query resolution, both simplifying the code and enabling overwrites.

### CODE REVIEW

**Comment by spawnia** [comment]
@ruudk please review.

**Comment by ruudk** [comment]
This week I'm busy with other things but I'll try to find some time next week to try this out. Thanks for this PR. 🙏🏻

**Comment by spawnia** [comment]
Btw, I am targeting `master`/`v15` with this pull request. Given there is slight potential of breakage, I wonder if we should even backport to v14.

I have tried out this branch in `nuwave/lighthouse`, where we have the `EnumType` implementation I previously mentioned to you. Everything seems to be fine.

**Comment by ruudk** [comment]
I checked the tests and it looks good.

When merged I can also try it out by using the v15/dev version.

**Comment by spawnia** [comment]
> When merged

done!

**Comment by ruudk** [comment]
It seems that I'm blocked by overblog/graphql-bundle not being compatible yet with `dev-master`. Would it be possible to also backport this to v14?

**Comment by spawnia** [comment]
Nope, the potential for breakage is too high.

**Pull request merged**
