### PR TITLE
Replace node kind checks by InstanceOf checks

### PR DESCRIPTION
**Pull request by simPod**
This allows better code analysis as every tool/IDE knows what object type goes into a condition branch

### CODE REVIEW

**Comment by mfn** [comment]
The `switch (true)` _truly_ reads weird.

On a related note: shouldn't all those `switch` statements have a "default: throw…" case? I noticed some have, some don't (I know, existing code).

**Comment by simPod** [comment]
Yup, it is indeed but PHP has no better way yet (though I believe it might be changed in the future).

I suppose I could add a default throw, that would make sense as all logical branches would be covered then 👍

**Comment by simPod** [comment]
Seems like `default: throw...` statemens are not there for a reason (eg. they're handled later).

**Comment by mfn** [comment]
Ops 🤷‍♀️ Who would knew…

**Comment by vladar** [comment]
One reason why `instanceof` checks were not used there in the first place was performance. I was 100% sure that strict equality checks were faster than `instanceof`.

So changes like this do require some benchmarking (and we don't have a good enough benchmark for such things in our phpbench yet). I think we need some bench for a query with ~2000 field calls (and ideally make sure all changed paths are affected).

Those micro-optimizations seem minor, but when we sum them up and then multiply x 1000 (or more) - it becomes noticeable.

**Comment by simPod** [comment]
Started with a micro benchmark

```php
<?php

class A
{
    public $kind = 'A';
}

$s = microtime(true);
for ($i = 0; $i < 10000000; $i++) {
    $a = new A();

    if ($a instanceof A) {
    }
}
var_dump(microtime(true) - $s);

$s = microtime(true);
for ($i = 0; $i < 10000000; $i++) {
    $a = new A();

    if ($a->kind === 'A') {
    }
}
var_dump(microtime(true) - $s);
```

On PHP 7.2
```
double(7.4557127952576)

double(7.6205501556396)
```

**Comment by mfn** [comment]
wow, why do our numbers differ so much?

```
php -v
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
$ php bench.php
float(0.53607106208801)
float(0.6186990737915)
$ php bench.php
float(0.49281096458435)
float(0.59114003181458)
$ php bench.php
float(0.4991409778595)
float(0.6029200553894)
```
But yeah, `instanceof` seems to be fater.

Did you maybe forget a 0? In that case I get:
```
$ php bench.php
float(5.1001918315887)
float(6.1185019016266)
```

**Comment by simPod** [comment]
Left xdebug enabled ;) With `php -n` having similar numbers

**Comment by simPod** [comment]
@vladar just checked HugeSchemaBench and it seems that it does query operations on huge schema 🤔

**Comment by vladar** [comment]
Those benches just test instanceof hits, not misses. There are actually several use cases we need to bench: hits, misses, hits and misses on the parent type (like a extends b, $a instanceof b). I think the latest one is the one we actually use the most.

**Comment by simPod** [comment]
What about this

```php
<?php

class A
{
    public $kind = 'A';
}

class B extends A
{
}

$s = microtime(true);
for ($i = 0; $i < 10000000; $i++) {
    $b = new B();

    if ($b instanceof A) {
    }
}
var_dump(microtime(true) - $s);

$s = microtime(true);
for ($i = 0; $i < 10000000; $i++) {
    $b = new B();

    if ($b->kind === 'A') {
    }
}
var_dump(microtime(true) - $s);
```

```
float(0.54834389686584)
float(0.62606191635132)
```

--------------

```php
<?php

class A
{
    public $kind = 'A';
}

class B extends A
{
}

$s = microtime(true);
for ($i = 0; $i < 10000000; $i++) {
    $b = new B();

    if (!$b instanceof A) {
    }
}
var_dump(microtime(true) - $s);

$s = microtime(true);
for ($i = 0; $i < 10000000; $i++) {
    $b = new B();

    if ($b->kind !== 'A') {
    }
}
var_dump(microtime(true) - $s);
```

```
float(0.62735915184021)
float(0.65307688713074)
```

**Comment by vladar** [comment]
I am on christmas/ny vacation at the moment, will get back to it later.

**Pull request merged**
