### PR TITLE
Ensure `InputObjectType::parseValue()` works with literals and extended schemas

### LINKED ISSUE #1178: InputObjectType parse value not working
Its documented under: https://webonyx.github.io/graphql-php/type-definitions/inputs/#converting-input-object-array-to-value-object

But it simply arrives as array.

I was able to follow it down to https://github.com/webonyx/graphql-php/blob/master/src/Utils/AST.php#L392-L435

its simply not called at all.

### PR DESCRIPTION
**Pull request by Warxcell**
Fixes #1178

### CODE REVIEW

**Comment by Warxcell** [comment]
@spawnia saw the actual bug - when extended parseValue is not transferred into new InputObjectType. Fixed it.

**Comment by spawnia** [comment]
@Warxcell great job on the test and the fix, thank you.

I am not quite sure if `parseValue` would work when providing the values as GraphQL literals (not using variables). Could you add a test for that too and make sure it works?

**Comment by Warxcell** [comment]
Yep, seems its not working.

**Comment by spawnia** [comment]
I think the place where this conversion was previously added was fundamentally wrong, because variable values are kept separate from value literals after that. A client might send a query like this:

```graphql
query ($foo: Int) {
  foo(input: { foo: $foo, bar: 2 })
}
```

In that case, both sources of values will have to be combined - only then can `InputObjectType::parseValue()` be called. I think the stacktrace you did in https://github.com/webonyx/graphql-php/issues/1178#issuecomment-1158819536 pretty much points to the correct place to do this.

**Comment by Warxcell** [comment]
Seems its needed on both places. That way probably it won't work when using mixed (raw variables and literals). 

If I put it inside `Values.php` - i should traverse from deeper level in order for upper levels to receive correct types.

**Comment by spawnia** [comment]
Thanks @Warxcell for your work on this.

**Pull request merged**
