### PR TITLE
Fix CS in Validator folder

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by mfn** [comment]
Soo many changes 😱 Was this all automatic or did you use a tool?

**Comment by simPod** [comment]
@mfn some changes were automatic, some not :) I was working on in for a few days when I had a spare time.

@mcg-web sure it my listing correct that `ValidationRule` and `QuerySecurity` (will rename to `QuerySecurityRule`) are those BC? Have I missed something else?

**Comment by mcg-web** [comment]
@simPod this look good to me

**Comment by vladar** [comment]
Thanks!

**Pull request merged**
