### PR TITLE
Add support for empty descriptions

### PR DESCRIPTION
**Pull request by vhenzl**
See https://github.com/graphql/graphql-js/pull/2177

Depends on #938.

### CODE REVIEW

**Comment by spawnia** [comment]
Ready to go, since #938 is merged?

**Comment by vhenzl** [comment]
Ready to go.

**Comment by vhenzl** [comment]
@spawnia Could these rules like "multiline ternary" be enforced by the linter?

**Comment by simPod** [comment]
I'll set it up.

**Pull request merged**
