### PR TITLE
Add PHP 8.4 to CI matrix

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by spawnia** [comment]
@simPod This pull request seems to be blocked because the checks `composer-normalize` and `php-cs-fixer` are now required. I can not seem to bypass this, and it seems like I can not access the setting that would make them not required. Do you have permissions I do not have in the project, or am I looking in the wrong place?

**Comment by ruudk** [comment]
If you have access to the settings, it could be that they use the new rulesets feature located in https://github.com/webonyx/graphql-php/settings/rules

**Comment by spawnia** [comment]
Yeah, I am getting a 404 for that page. Summoning @vladar, can you extend my permissions?

**Comment by simPod** [comment]
It's here 

https://github.com/webonyx/graphql-php/settings/branch_protection_rules/12748505

why are they not running 🤔

**Comment by simPod** [comment]
I've removed those Required rules, try force pushing to trigger creation of new actions.

**Comment by ruudk** [comment]
https://github.com/webonyx/graphql-php/blob/0420ef7c19347606f56ff096f62f9f7d489fb1aa/.github/workflows/test.yml#L4

It should have pull_request too

**Comment by ruudk** [comment]
Fixed it :)

**Comment by ruudk** [comment]
Removed it, those required checks need to be removed... or, the auto format thing needs to be revisited.

**Comment by simPod** [comment]
merged in https://github.com/webonyx/graphql-php/pull/1639

I've also cleanup all autoformats from required checks. Should be fine now.

**Pull request closed without merging**
