### PR TITLE
DO NOT MERGE: Drop Travis

### PR DESCRIPTION
**Pull request by simPod**
https://github.com/webonyx/graphql-php/issues/574#issuecomment-569678316

GA test:

- [x] test CS break
- [x] test PHPStan break
- [x] test unit test break

To compare with Travis run https://travis-ci.org/webonyx/graphql-php/builds/632608253

### CODE REVIEW

**Comment by simPod** [comment]
@vladar ping me when ready and I'll rebase+cleanup this.

**Comment by vladar** [comment]
@simPod Can you please clarify - ready to what? 😄 I thought this PR is just to compare failures with Travis. Am I missing something?

**Comment by simPod** [comment]
@vladar right 😀, I'd drop the Travis in this when we decide it's ready

**Comment by vladar** [comment]
@simPod I think we can drop Travis when you have a chance. But I suggest doing it in another PR! Will close this one.

**Pull request closed without merging**
