### PR TITLE
Bump PHPUnit to v9

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Review by spawnia — APPROVED** [review]

**Comment by simPod** [comment]
This fixes https://github.com/webonyx/graphql-php/pull/819. Sorry about the timing 🙃

**Comment by spawnia** [comment]
I still think #819 is fine. While in a PR, declining coverage is actionable. Once merged, the failing status is only a nagging eyesore.

**Comment by spawnia** [comment]
🚢

**Pull request merged**
