### PR TITLE
v15.18.1

### PR DESCRIPTION
**Pull request by spawnia**

### CODE REVIEW

**Comment by spawnia** [comment]
@simPod I can't push those changes directly to `master` anymore. I assume this is due to branch protection settings, which I am also unable to access. Can you give me the necessary permissions? I wonder why you have them and I do not.

**Comment by simPod** [comment]
Do you have any error message on push from github.

image

image

I don't see any relevant settings to it.

**Comment by simPod** [comment]
But I was able to give you admin

image

**Comment by spawnia** [comment]
I can push now that I am admin, thanks.

**Pull request merged**
