### PR TITLE
feat: narrow errors type to list

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by spawnia** [comment]
Thank you, released with https://github.com/webonyx/graphql-php/releases/tag/v15.14.1.

**Comment by shadowhand** [comment]
TIL about `list` as a type hint. 🙇🏽‍♂️

**Comment by simPod** [comment]
@shadowhand check this out https://phpstan.org/writing-php-code/phpdoc-types

**Comment by shadowhand** [comment]
@simPod ah, because `list` has only existed since phpstan 1.9.0 and later. I knew of `Foo[]` but not `list<Foo>`. 👍🏼

**Pull request merged**
