### PR TITLE
RFC: PHP CS

### PR DESCRIPTION
**Pull request by simPod**
Following https://github.com/webonyx/graphql-php/issues/284

- Added Code Sniffer with Doctrine CS
- Min PHP v is 7.1 as it's constraint for modern CS
- Fixed CS in `src/Errors`

For smoother transition typehint checks are now disabled and only modified lines are checked for CS compliance.

Doctrine and Slevomat CS require PHP ^7.1. Not sure, what's the roadmap of this project, can be merged after the PHP version constraint is set to not-outdated PHP versions.

### CODE REVIEW

**Comment by vladar** [comment]
Next major version (0.13) will use PHP7.1+, so we can start converting the code to PHP 7.1

**Comment by vladar** [comment]
Will this PR check pull requests only or will it fail builds after a regular push as well (if coding standard is not followed)?

**Comment by simPod** [comment]
For PRs, it will only check lines changed so people don't have to fix the whole file for build to pass but only their changes must be compliant.

Otherwise, it starts full check when not PR.

**Comment by vladar** [comment]
Can you also add composer scripts for linting and fixing?

**Comment by vladar** [comment]
Yes. At least linting the whole project. We can probably add fixing the whole project later %)

**Comment by vladar** [comment]
@simPod I've merged the PR, but it looks like it checks the whole project. Now build is failing on code style (with a ton of errors).

I doubt that we'll have enough time soon to fix all code style errors, so can you double check that it actually only checks PRs and maybe send a fix for it?

**Comment by vladar** [comment]
Actually, ignore it. I commented out a check of the whole project. Only new PRs are checked for now.

**Pull request merged**
