### PR TITLE
Use Coveralls, drop Scrutinizer

### PR DESCRIPTION
**Pull request by simPod**
I was not very satisfied with Scrutinizer in several past weeks (a lot of false positives, bugs etc.).

I though might be good idea to switch to something else. Tried to replace it with Coveralls. WDYT?

You can see the report here: https://coveralls.io/github/simPod/graphql-php

Also dropped the coverage from Travis as we plan to switch to GA anyways in #601.

@vladar If we decide to go with it, we just need to register repository on Coveralls.io and add repo token as a new secret:

image

### CODE REVIEW

**Comment by Smolevich** [comment]
@simPod, this [library](https://github.com/cedx/coveralls.php) supports GIthub Actions
I prepare PR here https://github.com/php-coveralls/php-coveralls/pull/275, but this in paused

**Comment by simPod** [comment]
@Smolevich thanks for links. Is there anything particular you would like to point out?

**Comment by simPod** [comment]
@vladar do not forget to [add the secret](https://github.com/webonyx/graphql-php/settings/secrets)

**Comment by vladar** [comment]
Yeah, just added it

**Comment by simPod** [comment]
I have to yet figure out why the coverage is not being linked to branches.

**Comment by vladar** [comment]
Yeah, noticed it too

**Comment by simPod** [comment]
@Smolevich ok, now I get what you meant. Cool!

**Pull request merged**
