### PR TITLE
Fix BC

### PR DESCRIPTION
**Pull request by mcg-web**
hi v0.13.2 introduce a BC since changing the signature or a public or a protected method is not allowed in patch releases

### CODE REVIEW

**Comment by simPod** [comment]
If only it was in docblock before :( :D

**Comment by vladar** [comment]
Technically 0.x.x versions are not considered stable and [anything can change at any time](https://semver.org/spec/v2.0.0.html#spec-item-4).

But yeah, we consider our releases stable, so I've merged this. FYI, we will switch to 14.0.0 for the next release (same as the reference implementation).

**Comment by mcg-web** [comment]
Thank you for the information, after more than 3 years of usage in production this is more than stable right now 😁.

**Comment by serbanbjd** [comment]
This fix is breaking maxDepth check, because now in QueryDepth::isEnabled $this->getMaxQueryDepth will return false, and $this->getMaxQueryDepth() !== self::DISABLED will return true

**Comment by mcg-web** [comment]
did not see [this change](https://github.com/webonyx/graphql-php/blob/0.13.x/src/Validator/Rules/QueryDepth.php#L106), this line was forced to integer in previous releases since it does not exists anymore `maxQueryDepth` must be an integer.

**Comment by vladar** [comment]
@mcg-web Mind sending another PR for this?

**Comment by mcg-web** [comment]
done #477 !

**Pull request merged**
