### PR TITLE
Align `SchemaPrinterTest` with `graphql-js` v15.5

### PR DESCRIPTION
**Pull request by vhenzl**
Aligns `SchemaPrinterTest.php` with `printSchema-test.js` from the reference implementation v15.5 as much as possible.

Relevant changes in `graphql-js`:
- https://github.com/graphql/graphql-js/commit/34b7ced883ff813a1d2d13c5fd58ba8158d69b60
- https://github.com/graphql/graphql-js/commit/4fcef75248a3db75da6080ed889ea2ce26a29928
- https://github.com/graphql/graphql-js/commit/ea089e016f1526fb5b5137b5f8a8739ec17b322c

TBD:
- [ ] different order of printed types (interfaces, unions)
- [ ] outdated introspection
- [ ] schema with description

Depends on #940, conflicts with #938 (shouldn't matter much but probably better merge #938 first)

### CODE REVIEW

**Comment by vhenzl** [comment]
@spawnia why are you pushing unrelated changes to this PR?

**Comment by spawnia** [comment]
> @spawnia why are you pushing unrelated changes to this PR?

Which changes in particular are you refering to? Given the commit messages, is something unclear?

**Comment by vhenzl** [comment]
Commits messages and the changes are clear, but "Use type alias for options" and "Move public api to top of the file" doesn't belong here. This PR is about aligning `SchemaPrinterTest.php` with `graphql-js`. You are adding completely unrelated changes to `SchemaPrinter.php`. Push each of them directly to master.

**Comment by spawnia** [comment]
@vhenzl integrated the changes from #938.

**Comment by spawnia** [comment]
I get what you mean, the changes were not necessary for the stated goal of this PR. They did however aid me in reviewing your changes and ensure that everything is still coherent. For larger pull requests like this one, I find it easier to simply view entire files at once and fix any issues local to those files.

I will attempt to isolate those changes in the future if they are difficult for you to deal with.

**Review by spawnia — APPROVED** [review]
We can merge this PR as-is and iterate on the TBD. @vhenzl do you think this is ready to go?

**Comment by vhenzl** [comment]
Well, first of all, you should first have look at and merge #940 on which this PR depends, as I noted in the description. It's an isolated change with a much smaller surface. Then I would rebase this one and marked ar ready for review (in a draft on purpose).

**Comment by spawnia** [comment]
> merge #940

done.

**Comment by spawnia** [comment]
I appreciate your work on this and am trying my best to integrate your changes after a few weeks of my absence. Looking forward to a great v15 release!

**Comment by vhenzl** [comment]
No worries! I'll have look at this tomorrow, I have already midnight here…

**Comment by vhenzl** [comment]
Replace with #955

**Pull request closed without merging**
