### PR TITLE
Warn about orphaned object types

### PR DESCRIPTION
**Pull request by quadrifolia**
Better error when the object type is not available because it is only used as object type within an interface. The "multiple types" error on ($runtimeType !== $this->exeContext->schema->getType($runtimeType->name)) is misleading, because the type is not available in the schema at all.

### CODE REVIEW

**Comment by mfn** [comment]
Shouldn't there be a test for this?

**Comment by quadrifolia** [comment]
Probably yes. I just did a quick edit within the github website. It is just a new error message (no type detected) for [this problem](https://github.com/webonyx/graphql-php/issues/378) that took me some time because the existing error message (multiple types detected) led me into the wrong direction.

**Comment by vladar** [comment]
This is useful. But this PR breaks the build (in the coding style) + we need some tests for this

**Comment by spawnia** [comment]
@quadrifolia are you still interested in pursuing this PR?

**Pull request merged**
