### PR TITLE
add support for NullValue

### PR DESCRIPTION
**Pull request by AndreasHeiberg**
https://github.com/facebook/graphql/pull/83

The new version of the spec allows for null values

### CODE REVIEW

**Comment by vladar** [comment]
Thanks for PR! But actual implementation for null values affects a bit wider scope than just AST and Parser. See https://github.com/graphql/graphql-js/pull/544 for reference. 

I can merge this PR as is, but if you wish to contribute other missing pieces as well - that would be great. If not - nevermind, since I plan to work on this further sometime soon, will use your PR as a base then.

**Comment by AndreasHeiberg** [comment]
Will I mainly needed this related to the other PR I sent to you. Probably won't have time to look into this before you fix it :)

**Comment by vladar** [comment]
Will merge it when I start the work on importing new features from reference implementation for 8.0.

**Comment by vladar** [comment]
Support for NullValues is in master now

**Pull request closed without merging**
